### ISSUE TITLE
[Admin] Implement participant check-in system

### ISSUE THREAD

**Issue by samderanova** [HackAtUCI/irvinehacks-site#266]
Organizers on check in will need an easy interface to check people in to our event. The main tasks for this are as follows:

- [x] #267
- [x] #268
- [x] #269
- [x] #279
- [x] #318
- [x] #355
- [x] #364

and if time permits:
- Include [Onboarding](https://cloudscape.design/patterns/general/onboarding/) process with [Help system](https://cloudscape.design/patterns/general/help-system/) and [Hands-on tutorials](https://cloudscape.design/patterns/general/onboarding/hands-on-tutorials/)

**Comment by taesungh** [comment]
Closing since core tasks were completed and successfully used during the event. Will create follow-up issue about onboarding/help system.
