### ISSUE TITLE
[Admin Site] Create separate page to facilitate participant check-in process

### ISSUE THREAD

**Issue by samderanova** [HackAtUCI/irvinehacks-site#269]
The third step of the check-in construction is to create a new page on the admin site to provide check-in members with an easy way to check people in. It should contain a table view for participants containing the name, UID, status, and role obtained from #268, along with an actions menu where one can choose whether to promote the current user off the waitlist or check them in. Since we use Cloudscape for the admin portal at the moment, see the [Cloudscape demo](https://cloudscape.design/examples/react/table.html) for an example on how to implement this. No need to provide a column for checkboxes because we'll be checking in one person at a time instead of checking multiple people in at once.

- [x] #334
- [x] #339
- [x] #340
- [x] #343
- [x] #344
- [x] If time permits: collection preferences

**Comment by taesungh** [comment]
As noted in #315, only certain check-in leads will be allowed to promote users from the waitlist through the endpoint provided by #307/#316. We'll also want a feature to confirm attendance for non-hackers as noted in #318.

**Comment by taesungh** [comment]
Considering complete as core functionality was added and used during the event. Continuation work for improvements described in #407 and #408.
