### ISSUE TITLE
Release Hacker, Mentor, and Volunteer Applications

### ISSUE THREAD

**Issue by waalbert** [HackAtUCI/irvinehacks-site#386]
All applications will open December 6th.
- Mentor and volunteer applications are moving from Google Forms to our site, so our backend will need to be modified accordingly.
- On the Home Page, a section representing hacker, mentor, or volunteer applications called "Choose your character" needs to be added. 
- The hacker application form can be updated from the last application form. 
  - route `/apply` can stay the same
- Mentor and Volunteer application forms will need to be created. 
  - routes `/mentor` and `/volunteer` need to be created
- On your local dev environment, there's a dev route `/api/dev/impersonate/<uid>` where you can sign in as `<uid>` and simulate this user's identity. 
  - To test application submission, disable `upload_resume` and `send_application_confirmation_email` in the backend api route `/apply` so you can submit applications using this user. 
  - This user will be on your local instance of MongoDB `localhost:8081` under database `irvinehacks-prod` and collection `users`
  - login credentials is username - admin, password - pass

---
General
- [x] #397
- [x] #405
- [x] #410
- [x] #441
- [x] #475 

Other API restructuring
- [x] #421
- [x] #422

Application Flow
- [x] #463
- [x] #459

Portal
- [x] #398

Hacker applications
- [x] #400
- [x] #461
- [x] #467

Mentor and volunteer applications
- [x] #395
- [x] #396
- [x] #470
- [x] #448
- [x] #450
- [x] #452

Unplanned
- [x] #482

To handle later
- #460
- #462

**Comment by IanWearsHat** [comment]
- [ ] #397
- [ ] #396 
- [ ] #395 
- [ ] #398

**Comment by waalbert** [comment]
Closing as all tasks have been completed
