### ISSUE TITLE
Create Application Data Models for Mentors and Volunteers

### ISSUE THREAD

**Issue by waalbert** [HackAtUCI/irvinehacks-site#448]
Right now, only hacker apps have a validation model in our backend, and due to the other apps having different questions, validation models will need to be created for those.

**Comment by taesungh** [comment]
Please also include the email from the user identity in the processed application data to assist with #454 and to save some trouble when the time comes to release decisions.

**Comment by taesungh** [comment]
Please track above request in a new issue, thanks.

**Comment by taesungh** [comment]
Note: looks like the `resume_share_to_sponsors` input is not tracked in the mentor application data.
