### ISSUE TITLE
Show application type in application preface

### ISSUE THREAD

**Issue by waalbert** [HackAtUCI/irvinehacks-site#459]
It would be useful for the user who's applying to easily see which application they're agreeing to the terms for in `ConfirmationDetails`. Currently, they can only see which application they're applying for on the actual form itself (not including the URL).

**Comment by taesungh** [comment]
Might also help to bring back the message for the other roles we had before
> Interested in helping out instead? Consider applying to be a mentor or a volunteer

**Comment by waalbert** [comment]
#460

**Comment by waalbert** [comment]
Completed in #471
