### ISSUE TITLE
Remove dependency on React Three Fiber

### ISSUE THREAD

**Issue by IanWearsHat** [HackAtUCI/irvinehacks-site#493]
Currently, the site uses React Three Fiber. I don't think we use any features from Three.js nor do we need any.

This would also remove a bug that someone experienced in #309.

**Comment by waalbert** [comment]
Yes, Three.js was used for the IH 24 site with the fireflies effect. We won't be needing it for IH 25 (at least not yet and I don't think we ever need it).
