### ISSUE TITLE
Elevate search params used by `GuestLoginVerificationForm`

### ISSUE THREAD

**Issue by taesungh** [HackAtUCI/irvinehacks-site#521]
Noticed in #403:

The [`GuestLoginVerificationForm` calls `useSearchParams`](https://github.com/HackAtUCI/irvinehacks-site/blob/3752272e3bba64e62ded6441b3a79d095e11ed2d/apps/site/src/app/(main)/guest-login/components/GuestLoginVerificationForm.tsx#L15) for the user's email and the `return_to` location. At build time, Next.js currently thinks this page can be statically rendered because of #168, but [Static Rendering for `useSearchParams`](https://nextjs.org/docs/app/api-reference/functions/use-search-params#static-rendering) requires a suspense boundary to avoid de-opting to client-side rendering.

With Next.js 13, this wasn't surfaced, but when attempting to build with Next.js 14, this causes an error:
> site:build: ⨯ useSearchParams() should be wrapped in a suspense boundary at page "/guest-login". Read more: https://nextjs.org/docs/messages/missing-suspense-with-csr-bailout

To fix this, we can either force dynamic rendering on the page (or properly fix #168) or rely on the page's [`searchParams`](https://nextjs.org/docs/14/app/api-reference/file-conventions/page#searchparams-optional) and pass those as props to the verification form component. This will unblock upgrading to Next.js 14.

Another option is having the form component use [Streaming with Suspense](https://nextjs.org/docs/14/app/building-your-application/routing/loading-ui-and-streaming#streaming-with-suspense), but this Guest Login page is inherently dynamic and doesn't really need such optimization, especially when there are no database queries.

**Comment by taesungh** [comment]
Note: with #525, Next.js will properly recognize that the page needs to be dynamically rendered, so this no longer blocks the version upgrade, but I think it would still be good to handle search params on the server to simplify things: `GuestLoginVerificationForm` itself would no longer need to be a client component.otherwise.

**Comment by waalbert** [comment]
I will switch `GuestLoginVerificationForm` to use `searchParams` from `GuestLogin`, so `GuestLoginVerificationForm` would not need to be a client component.
